USE [ERP_ECHA]
GO
/****** Object:  StoredProcedure [SPV].[USP_T_ORDEN_PEDIDO_INSERTAR_VALE_VERSION_21]    Script Date: 20/01/2026 10:45:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROC [SPV].[USP_T_ORDEN_PEDIDO_INSERTAR_VALE_VERSION_21]
(
@P_RUC_EMPRESA nvarchar(11),
@P_CODIGO_LOCALIDAD nvarchar(6),
@P_CODIGO_CE_COSTOS nvarchar(8),
@P_CODIGO_SC_COSTOS nvarchar(8),
@P_CODIGO_SS_COSTOS nvarchar(8),
@P_CODIGO_ORDENPEDIDO char(10) OUTPUT,
@P_NUMERO_ORDENPEDIDO varchar(50) OUTPUT,
@P_DOCUMENTO_INTERNO varchar(20) OUTPUT,
@P_INFORMACION_DOCUMENTO_INTERNO varchar(20),

@P_FECHA_EMISION smalldatetime,
@P_FECHA_ENTREGA smalldatetime,
@P_FECHA_VENCIMIENTO DATETIME = NULL,
@P_CODIGO_FORMA_PAGO nvarchar(2),
@P_CODIGO_VENDEDOR nvarchar(20),

@P_CODIGO_CLIENTE nvarchar(20),
@P_CODIGO_TIPODOC_IDENTIDAD_CLIENTE nvarchar(2) = '',
@P_RAZON_SOCIAL_CLIENTE varchar(150) = '',
@P_DIRECCION_FISCAL_CLIENTE varchar(200) = '',

@P_ITEM_DIRECCION_ENTREGA int,
@P_IGV_TASA numeric(18,7),

@P_TOTAL_VALOR numeric(18,7),
@P_TOTAL_DESCUENTO_P numeric(5,2),
@P_TOTAL_DESCUENTO_I numeric(18,7),
@P_TOTAL_VALOR_NETO numeric(18,7),
@P_INF numeric(18,7),
@P_BIM numeric(18,7),
@P_IGV numeric(18,7),
@P_TOTAL numeric(18,7),

@P_CODIGO_MONEDA nvarchar(2),
@P_CAMBIO_MONEDA numeric(6,3),
@P_OBSERVACION varchar(4000),
@P_USUARIO_CREA nvarchar(10),
@P_CODIGO_CAJA NVARCHAR(10),
@P_FECHA_REGISTRO DATETIME OUTPUT,
@P_REFERENCIA VARCHAR(20),
@P_FECHA_REFERENCIA DATETIME NULL,
@P_ID_ESTADO_OPERACION char(2),

@P_RESTAURANTE VARCHAR(100),

@P_CAMPO_01 varchar(max) = NULL,
@P_CAMPO_02 varchar(max) = NULL,
@P_CAMPO_03 varchar(max) = NULL,
@P_CAMPO_04 varchar(max) = NULL,
@P_CAMPO_05 varchar(max) = NULL,
@P_CAMPO_06 varchar(max) = NULL,
@P_CAMPO_07 varchar(max) = NULL,
@P_CAMPO_08 varchar(max) = NULL,
@P_CAMPO_09 varchar(max) = NULL,
@P_CAMPO_10 varchar(max) = NULL,
@P_CAMPO_11 varchar(max) = NULL,
@P_CAMPO_12 varchar(max) = NULL,
@P_CAMPO_13 varchar(max) = NULL,
@P_CAMPO_14 varchar(max) = NULL,
@P_CAMPO_15 varchar(max) = NULL,
@P_CAMPO_16 varchar(max) = NULL,
@P_CAMPO_17 varchar(max) = NULL,
@P_CAMPO_18 varchar(max) = NULL,
@P_CAMPO_19 varchar(max) = NULL,
@P_CAMPO_20 varchar(max) = NULL,
@P_CAMPO_21 varchar(max) = NULL,
@P_CAMPO_22 varchar(max) = NULL,
@P_CAMPO_23 varchar(max) = NULL,
@P_CAMPO_24 varchar(max) = NULL,
@P_CAMPO_25 varchar(max) = NULL,
@P_VALIDAR_ID_MOVIMIENTO_CAJA BIT = 0,
@P_TURNO varchar(3) OUTPUT,
@P_TOTAL_DSCTO_PRECIO_I NUMERIC(18,7),
@P_TOTAL_DSCTO_PRECIO_P NUMERIC(18,7),
@P_TOTAL_ANTICIPO NUMERIC(18,7),
@P_IB_ANTICIPO BIT,
@P_TOTAL_RECARGO_CONSUMO_I NUMERIC(16,7),
@P_TOTAL_RECARGO_CONSUMO_P NUMERIC(13,7),
@P_ID_MOTIVO_OPERACION INT,
@P_CODIGO_TIPOAUT INT = null,
@P_VALIDAR_FORMAPAGO_NROOPERACION BIT,
@P_TOTAL_ISC_I DECIMAL(18,7) = null,

@P_TOTAL_VALOR_GRATUITO NUMERIC(18,7) = 0.00,
@P_TOTAL_VALOR_GRATUITO_SINIMP NUMERIC(18,7) = 0.00,

@P_ID_SEGMENTO_VENTA INT = NULL,

@P_MENSAJE_RESULTADO nvarchar(MAX) OUTPUT
)
AS
BEGIN
	SET @P_MENSAJE_RESULTADO = ''

	IF @P_VALIDAR_FORMAPAGO_NROOPERACION = 1 AND COALESCE(@P_CAMPO_02,'') <> '' AND EXISTS(SELECT TOP(1)C_CODIGO_ORDENPEDIDO  FROM SPV.VW_T_ORDEN_PEDIDO WHERE C_RUC_EMPRESA = @P_RUC_EMPRESA AND C_CODIGO_FORMA_PAGO = @P_CODIGO_FORMA_PAGO AND COALESCE(C_CAMPO_02,'') = @P_CAMPO_02)
		SET @P_MENSAJE_RESULTADO += 'Ya existe forma de pago con numero de operación '+ @P_CAMPO_02
	ELSE
		BEGIN

			-- Vendedor --
			IF (ISNULL(@P_CODIGO_VENDEDOR,'') = '')
				SET @P_MENSAJE_RESULTADO += ' - Codigo Vendedor no existe' + CHAR(13) + CHAR(10)

			-- Moneda --
			IF (ISNULL(@P_CODIGO_MONEDA,'') = '')
				SET @P_MENSAJE_RESULTADO += ' - Codigo Moneda no existe' + CHAR(13) + CHAR(10)

			-- Movimiento de caja
			DECLARE @P_ID_MOVIMIENTO_CAJA INT = NULL

			IF (ISNULL(@P_VALIDAR_ID_MOVIMIENTO_CAJA,'0') = '1')
				BEGIN
					SELECT TOP(1) @P_ID_MOVIMIENTO_CAJA = MAX(C_ID_MOVIMIENTO_CAJA) FROM SPV.T_MOVIMIENTO_CAJA WHERE C_CODIGO_EMPRESA = @P_RUC_EMPRESA AND C_CODIGO_LOCALIDAD = @P_CODIGO_LOCALIDAD AND C_CODIGO_CAJA = @P_CODIGO_CAJA AND C_ESTADO = 0

					IF(ISNULL(@P_ID_MOVIMIENTO_CAJA,0) = 0)
						SET @P_MENSAJE_RESULTADO += '¡No hay ninguna caja aperturada!, '+CHAR(10)+'No se pudo asignar movimiento de caja a la orden pedido [orden pedido no ha sido registrado].'
				END

			IF (ISNULL(@P_MENSAJE_RESULTADO,'') = '')
				BEGIN
					-- Numero de pedido --
					SET @P_CODIGO_ORDENPEDIDO = (dbo.CD_OP(@P_RUC_EMPRESA))
					SET @P_NUMERO_ORDENPEDIDO = (dbo.Nro_OP(@P_RUC_EMPRESA))--(SPV.UFN_T_ORDEN_PEDIDO_GENERARNRO_OPERACION_INSERTAR(@P_RUC_EMPRESA))
				END

			IF (ISNULL(@P_MENSAJE_RESULTADO,'') = '')
				BEGIN
					SET @P_DOCUMENTO_INTERNO = (SELECT CONCAT(@P_DOCUMENTO_INTERNO,'-',ISNULL(MAX(CONVERT(INT,SUBSTRING(C_DOCUMENTO_INTERNO,4,LEN(C_DOCUMENTO_INTERNO)))),0) + 1)  FROM DBO.ORDPEDIDO WHERE RUCE = @P_RUC_EMPRESA AND (C_DOCUMENTO_INTERNO LIKE 'VA-%' OR  C_DOCUMENTO_INTERNO LIKE 'CA-%' OR C_DOCUMENTO_INTERNO LIKE 'OP-%') AND SUBSTRING(C_DOCUMENTO_INTERNO,1,2) = @P_DOCUMENTO_INTERNO)
					SET @P_FECHA_REGISTRO = GETDATE()
					--SET @P_NUMERO_ORDENPEDIDO = @P_CODIGO_ORDENPEDIDO -- SE AGREGO ESTA LINEA POR QUE AS ABAJO SE BLOQUEA AL INSERTAR
					SET @P_NUMERO_ORDENPEDIDO = dbo.Nro_OP(@P_RUC_EMPRESA)

					IF (COALESCE(@P_ID_ESTADO_OPERACION,'') = '')
					SET @P_ID_ESTADO_OPERACION = '01'
					IF (@P_CODIGO_TIPOAUT IS NULL)
					SET @P_CODIGO_TIPOAUT = 0

					INSERT INTO dbo.ORDPEDIDO
					(
						RUCE,
						CD_AREA,
						CD_CC,
						CD_SC,
						CD_SS,
						CD_OP,
						NROOP,
						FECE,
						FECENT,
						FECVENCIMIENTO,
						CD_FPC,
						CD_VDR,
						CD_CLT,
						CLIENTE,
						DIRECENT,
						C_ITEM_DIRECCION_ENTREGA,
						VALOR,
						TOTDSCTOP,
						TOTDSCTOI,
						VALORNETO,
						INF,
						INF_NETO,
						BIM,
						BIM_NETO,
						IGV,
						C_IGV_TASA,
						TOTAL,
						CD_MDA,
						CAMMDA,
						OBS,
						FECREG,
						USUCREA,
						Id_EstOP,
						CA01,
						CA02,
						CA03,
						CA04,
						CA05,
						CA06,
						CA07,
						CA08,
						CA09,
						CA10,
						CA11,
						CA12,
						CA13,
						CA14,
						CA15,
						CA16,
						CA17,
						CA18,
						CA19,
						CA20,
						CA21,
						CA22,
						CA23,
						CA24,
						CA25,
						C_INFORMACION_DOCUMENTO_INTERNO,
						C_DOCUMENTO_INTERNO,
						C_ID_MOVIMIENTO_CAJA,
						C_REFERENCIA,
						C_FECHA_REFERENCIA,
						C_RESTAURANTE,
						C_TOTAL_DSCTO_PRECIO_I,
						C_TOTAL_DSCTO_PRECIO_P,
						C_TOTAL_ANTICIPO,
						C_IB_ANTICIPO,
						C_TOTAL_RECARGO_CONSUMO_I,
						C_TOTAL_RECARGO_CONSUMO_P,
						C_ID_MOTIVO_OPERACION,
						TipAut,
						IB_Aut,
						C_FECHA_FACTURACION
						,C_ISCTotal
						,C_ID_APLICATIVO_REGISTRO
	
						,C_TOTAL_TRANS_GRATUITA
						,MontoTotalTG

						,C_ID_SEGMENTO_VENTA
						,C_FECHA_CADUCIDAD
						,C_SUB_TOTAL
					)  
					VALUES
					(
						@P_RUC_EMPRESA,
						@P_CODIGO_LOCALIDAD,
						@P_CODIGO_CE_COSTOS,
						@P_CODIGO_SC_COSTOS,
						@P_CODIGO_SS_COSTOS,
						@P_CODIGO_ORDENPEDIDO,
						@P_NUMERO_ORDENPEDIDO,
						@P_FECHA_EMISION,
						@P_FECHA_ENTREGA,
						@P_FECHA_VENCIMIENTO,
						@P_CODIGO_FORMA_PAGO,
						@P_CODIGO_VENDEDOR,
						@P_CODIGO_CLIENTE,
						@P_RAZON_SOCIAL_CLIENTE,
						@P_DIRECCION_FISCAL_CLIENTE,
						@P_ITEM_DIRECCION_ENTREGA,
						@P_TOTAL_VALOR,
						@P_TOTAL_DESCUENTO_P,
						@P_TOTAL_DESCUENTO_I,
						@P_TOTAL_VALOR_NETO,
						@P_INF,
						@P_INF,
						@P_BIM, 
						@P_BIM,
						@P_IGV,
						@P_IGV_TASA,
						@P_TOTAL,
						@P_CODIGO_MONEDA,
						@P_CAMBIO_MONEDA,
						@P_OBSERVACION,
						@P_FECHA_REGISTRO,
						@P_USUARIO_CREA,
						@P_ID_ESTADO_OPERACION,
						@P_CAMPO_01,
						@P_CAMPO_02,
						@P_CAMPO_03,
						@P_CAMPO_04,
						@P_CAMPO_05,
						@P_CAMPO_06,
						@P_CAMPO_07,
						@P_CAMPO_08,
						@P_CAMPO_09,
						@P_CAMPO_10,
						@P_CAMPO_11,
						@P_CAMPO_12,
						@P_CAMPO_13,
						@P_CAMPO_14,
						@P_CAMPO_15,
						@P_CAMPO_16,
						@P_CAMPO_17,
						@P_CAMPO_18,
						@P_CAMPO_19,
						@P_CAMPO_20,
						@P_CAMPO_21,
						@P_CAMPO_22,
						@P_CAMPO_23,
						@P_CAMPO_24,
						@P_CAMPO_25,
						@P_INFORMACION_DOCUMENTO_INTERNO,
						@P_DOCUMENTO_INTERNO,
						@P_ID_MOVIMIENTO_CAJA,
						@P_REFERENCIA,
						@P_FECHA_REFERENCIA,
						@P_RESTAURANTE,
						@P_TOTAL_DSCTO_PRECIO_I,
						@P_TOTAL_DSCTO_PRECIO_P,
						@P_TOTAL_ANTICIPO,
						@P_IB_ANTICIPO,
						@P_TOTAL_RECARGO_CONSUMO_I,
						(CASE WHEN ISNULL(@P_TOTAL_RECARGO_CONSUMO_P,0)>=1 THEN @P_TOTAL_RECARGO_CONSUMO_P ELSE @P_TOTAL_RECARGO_CONSUMO_P * 100 END),
						(CASE WHEN Coalesce(@P_ID_MOTIVO_OPERACION,0)=0 then null else @P_ID_MOTIVO_OPERACION end),
						(CASE WHEN Coalesce(@P_CODIGO_TIPOAUT,0)=0 then null else @P_CODIGO_TIPOAUT end),
						0,
						@P_FECHA_EMISION
						,@P_TOTAL_ISC_I
						,2

						,@P_TOTAL_VALOR_GRATUITO
						,@P_TOTAL_VALOR_GRATUITO_SINIMP

						,@P_ID_SEGMENTO_VENTA
						,@P_FECHA_VENCIMIENTO
						,@P_TOTAL_VALOR_NETO
					)

					IF @@ROWCOUNT <= 0
						SET @P_MENSAJE_RESULTADO = 'No se pudo insertar el pedido'

						SET @P_TURNO = (SELECT COUNT(C_ID_MOVIMIENTO_CAJA) FROM SPV.T_MOVIMIENTO_CAJA WHERE ISNULL(C_ID_MOVIMIENTO_CAJA,0) <= @P_ID_MOVIMIENTO_CAJA AND CONVERT(DATE,C_FECHA_MOVIMIENTO) = CONVERT(DATE,@P_FECHA_EMISION))
				END  
		END  
END